services:
   barotrauma:
      image: test/test
      container_name: barotrauma-server
      ports:
        - 27015:27015/udp
        - 27016:27016/udp
      environment:
         - SERVERNAME=testing
         - PASSWORD=password
         - OWNER_STEAMNAME=
         - OWNER_STEAMID=
         - MAX_PLAYERS=10
         - PORT=27015
         - QUERYPORT=27016
      volumes:
         - ./barotrauma-test-folder:/barotrauma/
      