name: Security Scan 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: build local container
        uses: docker/build-push-action@v2
        with:
          tags: thijsvanloef/barotrauma-server-docker:latest
          push: false
          load: true

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: "thijsvanloef/barotrauma-server-docker:latest"